### ISSUE TITLE
`window is not defined` Error on Build

### ISSUE THREAD

**Issue by AhmadHassan71** [VertoTechnologies/Chameleon#10]
# ReferenceError: window is not defined
The error occurs on the call page, when trying to render it for production build. This works fine on `npm run dev` as the page is not pre rendered.

```
Generating static pages (0/14)  [=   ]ReferenceError: window is not defined
    at new <anonymous> (D:\Node Projects\chameleon\.next\server\app\Call\page.js:49:17156)
    at D:\Node Projects\chameleon\.next\server\app\Call\page.js:49:16631
    at D:\Node Projects\chameleon\.next\server\app\Call\page.js:8:504
    at r (D:\Node Projects\chameleon\.next\server\app\Call\page.js:8:614)
    at T (D:\Node Projects\chameleon\.next\server\app\Call\page.js:176:70761)
    at 50266 (D:\Node Projects\chameleon\.next\server\app\Call\page.js:176:71616)
    at Object.t [as require] (D:\Node Projects\chameleon\.next\server\webpack-runtime.js:1:127)
    at require (D:\Node Projects\chameleon\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:16:18365)
    at I (D:\Node Projects\chameleon\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:94362)
    at D:\Node Projects\chameleon\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:96668 {
  digest: '3770813299'
}

Error occurred prerendering page "/Call". Read more: https://nextjs.org/docs/messages/prerender-error

ReferenceError: window is not defined
    at new <anonymous> (D:\Node Projects\chameleon\.next\server\app\Call\page.js:49:17156)
    at D:\Node Projects\chameleon\.next\server\app\Call\page.js:49:16631
    at D:\Node Projects\chameleon\.next\server\app\Call\page.js:8:504
    at r (D:\Node Projects\chameleon\.next\server\app\Call\page.js:8:614)
    at T (D:\Node Projects\chameleon\.next\server\app\Call\page.js:176:70761)
    at 50266 (D:\Node Projects\chameleon\.next\server\app\Call\page.js:176:71616)
    at Object.t [as require] (D:\Node Projects\chameleon\.next\server\webpack-runtime.js:1:127)
    at require (D:\Node Projects\chameleon\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:16:18365)
    at I (D:\Node Projects\chameleon\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:94362)
    at D:\Node Projects\chameleon\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:96668
 ✓ Generating static pages (14/14)

> Export encountered errors on following paths:
        /Call/page: /Call
```

## Steps to Reproduce
- `npm run build`
- Observe the build error related to "window not defined"

## Expected Behavior
The build process should complete successfully without encountering errors related to window being undefined.

## Actual Behavior
The build fails with a ReferenceError: window is not defined, indicating that server-side code is attempting to use window.

## Impact
This issue prevents the successful build of the project, which blocks deployment and further development.

## Environment
- Nextjs 14
- npm: 10.5.0
- node: 20.11.1

## Solutions Tried
- Dynamic Imports
- UseEffect containing an isClient state
- window!=='defined'

**Comment by AhmadHassan71** [comment]
# Issue has been Resolved!!
The thing causing the issue was the Agora RTC provider being loaded on the server side while prerendering. Putting it in a separate component and then dynamically importing it resolved the issue. Further more wrapping the Call component inside the AgoraProvider component fixed the calls in the production. They are now working on the deployment as well. 
You can check them out @ [https://chameleon-iota.vercel.app/](Chameleon Deployment)
